name = "merely-true"
defaultTargets = ["MerelyTrue"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.0"

[[lean_lib]]
name = "MerelyTrue"
globs = ["MerelyTrue.+"]

