/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/
import MerelyTrue.FormalLearningTheory.Basic
import Mathlib.Computability.TuringMachine.StackTuringMachine
import Mathlib.Computability.Primrec.List
import Mathlib.Computability.Partrec
import Mathlib.Computability.PartrecCode
import Mathlib.Computability.Encoding
import Mathlib.SetTheory.Ordinal.Arithmetic

/-!
# Computation and Formal Language Theory

Computability-theoretic substrate for Gold-style learning theory. Contains:
- Automata (DFA, NFA, PDA, Turing machines) with Mathlib bridges
- Formal languages (regular, context-free, recursively enumerable)
- Computability classes (partial computable, RE sets, Δ₀₂, limiting recursion)
- Information-theoretic primitives (Kolmogorov complexity, MDL, MML, SRM)
- Execution traces for program synthesis
-/

universe u v

/-!
## Alphabets and Formal Languages
-/

/-- An alphabet for formal language theory. Finite type with decidable equality. -/
class Alphabet (Sym : Type*) where
  [toFintype : Fintype Sym]
  [toDecidableEq : DecidableEq Sym]

/-- A word over an alphabet. -/
abbrev Word (Sym : Type*) := List Sym

/-- A formal language: a set of words. -/
def FormalLanguage (Sym : Type*) := Set (Word Sym)

/-!
## Automata

These are wrappers providing the learning-theoretic interface.
Mathlib has DFA/NFA; we bridge to those where possible.
-/

/-- Deterministic finite automaton. Bridge to Mathlib's `DFA`. -/
structure DFA' (Sym : Type*) (Q : Type*) [Fintype Q] [DecidableEq Q] where
  /-- Transition function -/
  step : Q → Sym → Q
  /-- Start state -/
  start : Q
  /-- Accept states -/
  accept : Set Q

/-- The language accepted by a DFA. -/
def DFA'.accepts {Sym : Type*} {Q : Type*} [Fintype Q] [DecidableEq Q]
    (M : DFA' Sym Q) : FormalLanguage Sym :=
  { w | List.foldl M.step M.start w ∈ M.accept }

/-- Nondeterministic finite automaton. -/
structure NFA' (Sym : Type*) (Q : Type*) [Fintype Q] where
  step : Q → Sym → Set Q
  start : Set Q
  accept : Set Q

/-- A regular language is a language accepted by some DFA. -/
def IsRegularLang (Sym : Type*) (L : FormalLanguage Sym) : Prop :=
  ∃ (Q : Type) (_ : Fintype Q) (_ : DecidableEq Q) (M : DFA' Sym Q), M.accepts = L

/-- Context-free grammar. -/
structure CFG (Sym : Type*) where
  /-- Nonterminal symbols -/
  Variable : Type
  /-- Production rules: Variable → list of (Variable ⊕ Terminal) -/
  productions : Variable → Set (List (Variable ⊕ Sym))
  /-- Start symbol -/
  start : Variable

/-- One-step CFG derivation: replace one nonterminal by a production. -/
def CFG.DerivesStep {Sym : Type*} (G : CFG Sym)
    (sf1 sf2 : List (G.Variable ⊕ Sym)) : Prop :=
  ∃ (pre suf : List (G.Variable ⊕ Sym)) (v : G.Variable)
    (p : List (G.Variable ⊕ Sym)),
    p ∈ G.productions v ∧
    sf1 = pre ++ [Sum.inl v] ++ suf ∧
    sf2 = pre ++ p ++ suf

/-- Multi-step CFG derivation: reflexive-transitive closure of one-step. -/
def CFG.Derives {Sym : Type*} (G : CFG Sym) :
    List (G.Variable ⊕ Sym) → List (G.Variable ⊕ Sym) → Prop :=
  Relation.ReflTransGen G.DerivesStep

/-- The language generated by a CFG: all terminal strings derivable from start. -/
def CFG.Language {Sym : Type*} (G : CFG Sym) : FormalLanguage Sym :=
  { w | G.Derives [Sum.inl G.start] (w.map Sum.inr) }

/-- A context-free language is a language generated by some CFG. -/
def IsContextFree (Sym : Type*) (L : FormalLanguage Sym) : Prop :=
  ∃ (G : CFG Sym), G.Language = L

/-- Pushdown automaton - extends DFA with a stack. -/
structure PDA (Sym : Type*) (Q : Type*) (Γ : Type*) where
  step : Q → Option Sym → Γ → Set (Q × List Γ)
  start : Q
  startStack : Γ
  accept : Set Q

/-!
## Computability Infrastructure

Critical for Gold-style learning: EX-learnability connects to the arithmetic hierarchy.
-/

/-- A Turing machine (abstract). We use this as an opaque type representing
    effective computability. Bridges to Mathlib's computability library. -/
structure TuringMachine where
  /-- Opaque representation; we work with the computability predicate, not the machine. -/
  index : ℕ

/-- Gödel numbering: an effective encoding of objects as natural numbers. -/
def GodelNumbering (α : Type*) := α ≃ ℕ

/-- Partial computable function. Bridges to Mathlib's `Computable` / `Partrec`.
    A function f : α →. β is partial computable iff there exists a Nat.Partrec function g
    on ℕ that commutes with the encodings: (f a).map encode = g (encode a).
    Note: uses Encodable (not Primcodable); the Partrec witness operates on codes. -/
def PartialComputable (α β : Type*) [Encodable α] [Encodable β] :=
  { f : α →. β // ∃ g : ℕ →. ℕ, Nat.Partrec g ∧
    ∀ a : α, (f a).map Encodable.encode = g (Encodable.encode a) }

/-- Recursively enumerable set. -/
def RESet (α : Type*) [Encodable α] := { S : Set α // ∃ f : ℕ → Option α, S = { a | ∃ n, f n = some a } }

/-- Limiting recursion: functions that converge in the limit.
    f is limiting-recursive if there exists a total computable g such that
    f(x) = lim_{s→∞} g(x, s). This is the computational substrate of EX-learning. -/
def LimitingRecursive (α β : Type*) [Encodable α] [Encodable β] :=
  { f : α → β // ∃ g : α → ℕ → β, (∀ x, ∃ s₀, ∀ s ≥ s₀, g x s = f x) }

/-- Δ₀₂ class: sets whose characteristic function is limiting-recursive.
    EX-learnable concept classes have Δ₀₂ membership. -/
def Delta02Class (α : Type*) [Encodable α] :=
  { S : Set α // ∃ f : α → ℕ → Bool, ∀ x, (x ∈ S ↔ ∃ s₀, ∀ s ≥ s₀, f x s = true) }

/-!
## Information-Theoretic Primitives
-/

/-- Kolmogorov complexity: the length of the shortest program that produces x.
    Defined via Nat.Partrec.Code (Mathlib's effective program codes).
    K(x) = inf { encode(p) : p.eval 0 = some (encode x) }.
    If no program produces x, sInf ∅ = 0 by convention (vacuous). -/
noncomputable def KolmogorovComplexity (α : Type*) [Encodable α] (x : α) : ℕ :=
  sInf { Encodable.encode p | (p : Nat.Partrec.Code)
    (_ : Nat.Partrec.Code.eval p 0 = Part.some (Encodable.encode x)) }

/-- Description length: length of encoding under a specific description language.
    Unlike Kolmogorov complexity, this is relative to a chosen coding scheme. -/
def DescriptionLength (α : Type*) := α → ℕ

/-- Minimum Description Length principle: choose the hypothesis that minimizes
    description_length(H) + description_length(data | H).
    Analogous to Kolmogorov complexity. Analogous to Bayesian MAP. -/
structure MDLPrinciple (X : Type u) (Y : Type v) [Inhabited (Concept X Y)] where
  /-- Description language for hypotheses -/
  hypothesisLength : Concept X Y → ℕ
  /-- Description language for data given hypothesis -/
  dataLength : Concept X Y → List (X × Y) → ℕ
  /-- MDL selection: minimize total description length.
      Uses Classical.epsilon to select an h ∈ H minimizing hypothesisLength h + dataLength h data.
      Inhabited provides the Nonempty witness for epsilon. -/
  select (data : List (X × Y)) (H : Set (Concept X Y)) : Concept X Y :=
    Classical.epsilon (fun h => h ∈ H ∧
      ∀ h' ∈ H, hypothesisLength h + dataLength h data ≤ hypothesisLength h' + dataLength h' data)

/-- Minimum Message Length: Bayesian analog of MDL.
    MML seeks the hypothesis that minimizes expected message length under
    a prior and likelihood model. -/
structure MMLPrinciple (X : Type u) (Y : Type v) [Inhabited (Concept X Y)] where
  hypothesisLength : Concept X Y → ℝ
  dataFit : Concept X Y → List (X × Y) → ℝ
  /-- MML selection: minimize total message length (hypothesisLength + dataFit).
      Inhabited provides the Nonempty witness for epsilon. -/
  select (data : List (X × Y)) (H : Set (Concept X Y)) : Concept X Y :=
    Classical.epsilon (fun h => h ∈ H ∧
      ∀ h' ∈ H, hypothesisLength h + dataFit h data ≤ hypothesisLength h' + dataFit h' data)

/-- Algorithmic probability: probability of x under the universal distribution.
    P(x) = Σ_{p : Code, p(0)=encode(x)} 2^{-|p|}. Related to Kolmogorov complexity by
    the coding theorem: -log P(x) ≈ K(x).
    Uses Classical.propDecidable for the halting condition (undecidable in general). -/
noncomputable def AlgorithmicProbability (α : Type*) [Encodable α] (x : α) : ℝ :=
  haveI : DecidableEq (Part ℕ) := Classical.decEq _
  ∑' (p : Nat.Partrec.Code),
    if Nat.Partrec.Code.eval p 0 = Part.some (Encodable.encode x)
    then (2 : ℝ) ^ (-(Encodable.encode p : ℤ))
    else 0

-- BayesianInference has been moved to Learner.lean (conceptually correct placement:
-- it's a learning-theory primitive, not a computability primitive).

/-- Structural Risk Minimization: choose hypothesis from the complexity level
    that minimizes bound on generalization error. Connects VC dimension
    to inductive bias. -/
structure SRM (X : Type u) (Y : Type v) [DecidableEq Y] [Inhabited (Concept X Y)] where
  /-- Nested hypothesis classes of increasing complexity -/
  levels : ℕ → Set (Concept X Y)
  /-- Monotonicity: larger index = richer class -/
  mono : ∀ n, levels n ⊆ levels (n + 1)
  /-- Empirical risk: fraction of training errors -/
  empiricalRisk : Concept X Y → List (X × Y) → ℝ
  /-- Complexity penalty: regularizer per level -/
  penalty : ℕ → ℝ
  /-- SRM selection: minimize empiricalRisk(h, data) + penalty(n) over (n, h ∈ levels n).
      Uses Classical.epsilon for the argmin; Inhabited provides the witness. -/
  select (data : List (X × Y)) : ℕ × Concept X Y :=
    Classical.epsilon (fun (pair : ℕ × Concept X Y) =>
      pair.2 ∈ levels pair.1 ∧
        ∀ n (h : Concept X Y), h ∈ levels n →
          empiricalRisk pair.2 data + penalty pair.1 ≤
            empiricalRisk h data + penalty n)

/-!
## Execution Traces (for process-level concepts)
-/

/-- An execution trace records the sequence of hypotheses a learner produces. -/
def ExecutionTrace (X : Type u) (Y : Type v) := ℕ → Concept X Y

/-- A partial trace that may not be defined at all time steps. -/
def PartialTrace (X : Type u) (Y : Type v) := ℕ → Option (Concept X Y)

